# Generated by Django 3.2.10 on 2022-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220207_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
