# Generated by Django 3.2.10 on 2022-02-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220207_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='chat',
        ),
    ]
